### ISSUE TITLE
Package does not exists/Depency not resolved

### ISSUE THREAD

**Issue by jeremypele** [NativeScript/functional-tests-demo#4]
Hi,

I just can't load the .jar dependencies through my tests suite cause the dependency is not resolved

On the first line of my test page
```
import functional.tests.core.mobile.element.UIElement;
```

And when I launch the test with `mvn clean test -P sim.iphone5.ios10`
```
package functional.tests.core.mobile.element does not exist
```

I registered the .jar with `mvn install:install-file` already

**Comment by karel1980** [comment]
Can you show the exact commands you're using?

**Comment by karel1980** [comment]
... Or not :)

**Comment by jeremypele** [comment]
Hi,

I've closed the issue, I was facing this august last year. 
Totally out of context right now, I'm myself unable to explain now what was wrong at the time.
I've switched to `nativescript-dev-appium` instead

Thanks

**Comment by karel1980** [comment]
yw ;)
